# list specialities faker
$specialities = [
  "Aeroespacial", 
  "Química", 
  "Civil", 
  "Mecánica", 
  "Producción", 
  "Biomédica", 
  "Sistemas", 
  "Ambiental", 
  "Mecatrónica", 
  "Eléctrica", 
  "Agrícola"
]

# list of faker courses
$courses = [
  'MATEMATICA BASICA',
  'MATEMATICA I',
  'TECNICAS DE PROGRAMACION',
  'INTROD. A LA ING. EN INFORMATICA Y SISTEMAS',
  'COMUNICACION Y REDACCION',
  'METODOLOGIA DEL TRABAJO UNIVERSITARIO',
  'ECOLOGIA',
  'MATEMATICA II',
  'ESTADISTICA I',
  'FISICA I',
  'TALLER DE PROGRAMACION I',
  'DIBUJO ASISTIDO POR COMPUTADORA',
  'FILOSOFIA',
  'MATEMATICA III',
  'ESTADISTICA II',
  'FISICA II',
  'MATEMATICAS DISCRETAS',
  'BASE DE DATOS',
  'METODOLOGIA DE LA INVESTIGACION',
  'MATEMATICA IV',
  'SISTEMAS DIGITALES I',
  'GESTION DE BASE DE DATOS',
  'ESTRUCTURA DE DATOS Y ALGORITMOS',
  'TEORIA GENERAL DE SISTEMAS',
  'CONTABILIDAD GENERAL',
  'ANALISIS NUMERICO COMPUTACIONAL',
  'SISTEMAS DIGITALES II',
  'TALLER DE PROGRAMACION II',
  'INGENIERIA DE SOFTWARE I',
  'METODOLOGIA DE SISTEMAS I',
  'INVESTIGACION DE OPERACIONES I',
  'ARQUITECTURA DE COMPUTADORAS',
  'INGENIERIA DE SOFTWARE II',
  'ECONOMIA',
  'REDES Y TELECOMUNICACIONES I',
  'DINAMICA DE SISTEMAS I',
  'INVESTIGACION DE OPERACIONES II',
  'REDES Y CONECTIVIDAD I',
  'SOFTWARE LIBRE BASICO',
  'SISTEMAS OPERATIVOS',
  'REDES Y TELECOMUNICACIONES II',
  'GESTION DE PROYECTOS',
  'METODOLOGIA DE SISTEMAS II',
  'ORGANIZACION Y DIRECCION DE EMPRESAS',
  'CREATIVIDAD EMPRESARIAL',
  'REDES Y CONECTIVIDAD II',
  'SOFTWARE LIBRE INTERMEDIO',
  'ARQUITECTURA DE PROCESADORES',
  'SISTEMAS DISTRIBUIDOS',
  'DINAMICA DE SISTEMAS II',
  'SISTEMAS DE INFORMACION',
  'GESTION DE RECURSOS HUMANOS',
  'SIMULACION DISCRETA DE SISTEMAS',
  'INTELIGENCIA DE NEGOCIOS',
  'REDES Y CONECTIVIDAD III',
  'SOFTWARE LIBRE AVANZADO',
  'INTELIGENCIA ARTIF. Y SIST. EXPERTOS',
  'SISTEMAS DE TIEMPO REAL',
  'TALLER DE SEGURIDAD INFORMATICA',
  'SISTEMAS DE INFORMACION GERENCIAL',
  'PLANEAMIENTO INFORMATICO',
  'SEMINARIO DE TESIS I',
  'REDES Y CONECTIVIDAD IV',
  'AUDITORIA DE SISTEMAS',
  'TALLER EN ING. EN INFORM. Y SISTEMAS',
  'SEMINARIO DE TESIS II',
  'DERECHO INFORMATICO',
  'GESTION DEL CONOCIMIENTO',
  'DEONTOLOGIA PROFESIONAL',
  'COMPUTACION GRAFICA',
  'DESARROLLO DE APLICACIONES WEB',
  'INGENIERIA DE REQUERIMIENTOS',
  'TOPICOS DE SIMULACION',
  'PRACTICAS PRE PROFESIONALES',
  'COMPILADORES',
  'CALIDAD DE SOFTWARE',
  'GESTION DE PROYECTOS INFORMATICOS',
  'NEGOCIOS ELECTRONICOS',
  'GESTION DEL CAMBIO',
  'GESTION DE TEC. LIMPIAS PARA EL DES. SOST.',
  'NEGOCIOS INTERNACIONALES',
  'SISTEMAS DE INFORMACION GEOGRAFICA',
  'CIENCIA, TECNOLOGIA Y SOCIEDAD',
  'INVESTIGACION TECNOLOGICA',
  'TECNOLOGIAS EMERGENTES',
  'PROSPECTIVA TECNOLOGICA'
];

# faker sections 
$sections = ('A'..'Z').to_a

# faker offices
$offices = (10..50).map do |num|
  $sections.sample(2).join + "-" + (num * 10).to_s
end

# limit num teachers
$num_teachers = 100

# limit num students
$num_students = 200

# limit num students
$num_registers = 500
